### ISSUE TITLE
You can't have an association of the same name with a different target "className" option anywhere in your app

### ISSUE THREAD

**Issue by anastasionico** [slince/cakephp-permission#1]
I have done everything as written in the doc and I have no problem until I try to give a permission to a specific role.

```
 $roleObj = Role::find($role->name);
 $roleObj->givePermission($addPermission);
```
Here is what I got dump&dying $roleObj before the second line of the previous snippet.

```
object(Slince\CakePermission\Model\Entity\Role)#239 (13) {
  ["id"]=>
  int(6)
  ["name"]=>
  string(5) "Admin"
  ["slug"]=>
  string(5) "Admin"
  ["created"]=>
  object(Cake\I18n\Time)#258 (3) {
    ["time"]=>
    string(25) "2018-08-22T11:41:28+00:00"
    ["timezone"]=>
    string(3) "UTC"
    ["fixedNowTime"]=>
    bool(false)
  }
  ["modified"]=>
  string(15) "22/08/18, 11:41"
  ["[new]"]=>
  bool(false)
  ["[accessible]"]=>
  array(2) {
    ["id"]=>
    bool(false)
    ["*"]=>
    bool(true)
  }
  ["[dirty]"]=>
  array(0) {
  }
  ["[original]"]=>
  array(0) {
  }
  ["[virtual]"]=>
  array(0) {
  }
  ["[errors]"]=>
  array(0) {
  }
  ["[invalid]"]=>
  array(0) {
  }
  ["[repository]"]=>
  string(16) "_PermissionRoles"
}
```

When I run the givePermission command I see this error

`Slince\CakePermission\Model\Table\RolesTable association "Permissions" of type "manyToMany" to "App\Model\Table\PermissionsTable" doesn't match the expected class "Slince\CakePermission\Model\Table\PermissionsTable". 
You can't have an association of the same name with a different target "className" option anywhere in your app.
`

I have looked for solutions but there is nothing relevant of this case.

Have I missed some step during the configuration?
Here are the relations I am try to use without success
```
$this->belongsToMany('Permissions', [
            'targetTable' => 'Slince\CakePermission\Model\Table\Permissions',
            'className' => 'Slince\CakePermission\Model\Table\Permissions',
            'foreignKey' => 'role_id',
            'targetForeignKey' => 'permission_id',
            'joinTable' => 'roles_permissions',
            'saveStrategy' => 'append'
 ]);
$this->belongsToMany('Roles', [
            'targetTable' => 'Slince\CakePermission\Model\Table\Roles',
            'className' => 'Slince\CakePermission\Model\Table\Roles',
            'foreignKey' => 'permission_id',
            'targetForeignKey' => 'role_id',
            'joinTable' => 'roles_permissions',
            'saveStrategy' => 'append'
]);
```

**Comment by slince** [comment]
Hi, it looks like that you are using your own "PermissionsTable"?

If so, you have to modify the `tableClassMap > Permissions`  in your app.php 

```php.
   'tableClassMap' => [
        /**
         * The Users model class, remember to modify it
         */
        'Users' => App\Model\Table\YourUsersTable::class,

        /**
         * The Roles model class;If you want to use the default configuration. you don't need to change.
         */
        //'Roles' => Slince\CakePermission\Model\Table\RolesTable::class,

        /**
         * The Permissions model class;If you want to use the default configuration. you don't need to change.
         */
        'Permissions' => App\Model\Table\YourPermissionsTable::class
    ]
```
And you dont need to build relations by yourself. you just need extends [`Slince\CakePermission\Model\Table\PermissionsTable`](https://github.com/slince/cakephp-permission/blob/master/src/Model/Table/PermissionsTable.php)

**Comment by anastasionico** [comment]
I have baked permissions, so everything is Cakephp-standard.
I have even tried to change the permissionTable in src into your version but it still does not work.
even changing the line in  app.php I still get the same error.

The thing is, Where this association is actually written?

**Comment by slince** [comment]
Hi, you need not create relations in your `RolesTable` and `PermissionsTable`,  If there is, please remove them.

**Comment by slince** [comment]
You just need to extend  `Slince\CakePermission\Model\Table\RolesTable` & `Slince\CakePermission\Model\Table\PermissionsTable`, `Slince\CakePermission\Model\Entity\Permission` and `Slince\CakePermission\Model\Entity\Role`

> If you don't add new fields to the roles and permissions tables, you can use the defaults without creating your own.

**Comment by anastasionico** [comment]
So, this is what I did to make it work:
// use Cake\ORM\Entity;
use Slince\CakePermission\Model\Entity\Permission as Entity;
// use Cake\ORM\Entity;
use Slince\CakePermission\Model\Entity\Role as Entity;
// use Cake\ORM\Table;
use Slince\CakePermission\Model\Table\RolesTable as Table;
// use Cake\ORM\Table;
use Slince\CakePermission\Model\Table\PermissionsTable as Table;

Basically, I have swept the built-it classes with the one of your package.
I do not know if it was only me, but this process was not very clear. it might worth add it to the documentation.

Anyway, Thanks a lot for your help
